import data from '@/lib/data/ueb-contracted.json';
import { fromUnicode, type Dots } from '@/lib/ueb';

const BRAILLE = (data as { braille: Record<string, string> }).braille;

/**
 * Contracted (UEB grade 2) cells for a print string, from liblouis output generated by
 * scripts/generate-ueb-oracle.ts. Throws if the string was never generated, so nothing
 * unchecked can reach the page.
 */
export function contractedCells(text: string): Dots[] {
  const unicode = BRAILLE[text];
  if (!unicode) throw new Error(`No contracted braille for "${text}". Add it to lib/ueb-corpus.ts and regenerate.`);
  return Array.from(unicode).map((ch) => fromUnicode(ch));
}

export function hasContracted(text: string): boolean {
  return text in BRAILLE;
}
