/** Answer words: 4-letter, common words good for braille learning */
export const answerWords = [
  'BOOK', 'CELL', 'DOTS', 'FEEL', 'GRIP',
  'HAND', 'KNOW', 'LAMP', 'MIND', 'NOTE',
  'PAGE', 'READ', 'SIGN', 'TALK', 'WANT',
  'WORD', 'BUMP', 'DASH', 'FUND', 'HELP',
];

/** Valid 4-letter guesses (includes answer words + extras) */
export const validGuesses = new Set([
  ...answerWords,
  'ABLE', 'ALSO', 'AREA', 'BACK', 'BAND', 'BASE', 'BEAR', 'BEAT',
  'BEEN', 'BELL', 'BEST', 'BILL', 'BIRD', 'BLOW', 'BLUE', 'BOAT',
  'BODY', 'BOLD', 'BOMB', 'BOND', 'BONE', 'BORN', 'BOTH', 'BURN',
  'BUSY', 'CAFE', 'CAGE', 'CAKE', 'CALL', 'CALM', 'CAME', 'CAMP',
  'CARD', 'CARE', 'CASE', 'CASH', 'CAST', 'CHAT', 'CHIP', 'CITY',
  'CLAM', 'CLAP', 'CLAY', 'CLIP', 'CLUB', 'CLUE', 'COAT', 'CODE',
  'COIN', 'COLD', 'COME', 'COOK', 'COOL', 'COPE', 'COPY', 'CORD',
  'CORE', 'CORN', 'COST', 'CREW', 'CROP', 'CUPS', 'CURE', 'CURL',
  'CUTE', 'DARE', 'DARK', 'DATA', 'DATE', 'DAWN', 'DAYS', 'DEAD',
  'DEAL', 'DEAR', 'DEBT', 'DECK', 'DEEP', 'DEER', 'DENY', 'DESK',
  'DIAL', 'DICE', 'DIET', 'DIME', 'DINE', 'DIRT', 'DISC', 'DISH',
  'DISK', 'DOCK', 'DOES', 'DOME', 'DONE', 'DOOM', 'DOOR', 'DOSE',
  'DOWN', 'DRAG', 'DRAW', 'DREW', 'DROP', 'DRUM', 'DUAL', 'DUCK',
  'DULL', 'DUMP', 'DUNE', 'DUSK', 'DUST', 'DUTY', 'EACH', 'EARN',
  'EASE', 'EAST', 'EASY', 'EDGE', 'EDIT', 'ELSE', 'EPIC', 'EVEN',
  'EVER', 'EVIL', 'EXAM', 'EXEC', 'EXIT', 'EYES', 'FACE', 'FACT',
  'FADE', 'FAIL', 'FAIR', 'FAKE', 'FALL', 'FAME', 'FARM', 'FAST',
  'FATE', 'FEAR', 'FEAT', 'FEED', 'FEET', 'FELL', 'FELT', 'FILE',
  'FILL', 'FILM', 'FIND', 'FINE', 'FIRE', 'FIRM', 'FISH', 'FIST',
  'FLAG', 'FLAT', 'FLED', 'FLEW', 'FLIP', 'FLOW', 'FOAM', 'FOLD',
  'FOLK', 'FONT', 'FOOD', 'FOOL', 'FOOT', 'FORD', 'FORK', 'FORM',
  'FORT', 'FOUL', 'FOUR', 'FREE', 'FROM', 'FUEL', 'FULL', 'FURY',
  'FUSE', 'GAIN', 'GAME', 'GANG', 'GAPS', 'GATE', 'GAVE', 'GAZE',
  'GEAR', 'GENE', 'GIFT', 'GIRL', 'GIVE', 'GLAD', 'GLOW', 'GLUE',
  'GOAL', 'GOES', 'GOLD', 'GOLF', 'GONE', 'GOOD', 'GRAB', 'GRAY',
  'GREW', 'GRIN', 'GROW', 'GULF', 'GURU', 'GUYS', 'HACK', 'HAIR',
  'HALF', 'HALL', 'HALT', 'HANG', 'HARD', 'HARM', 'HATE', 'HAUL',
  'HAVE', 'HAZE', 'HEAD', 'HEAL', 'HEAP', 'HEAR', 'HEAT', 'HEEL',
  'HELD', 'HERE', 'HERO', 'HIGH', 'HIKE', 'HILL', 'HINT', 'HIRE',
  'HOLD', 'HOLE', 'HOME', 'HOOD', 'HOOK', 'HOPE', 'HORN', 'HOST',
  'HOUR', 'HUGE', 'HUNG', 'HUNT', 'HURT', 'HYMN', 'ICON', 'IDEA',
  'INCH', 'INTO', 'IRON', 'ITEM', 'JACK', 'JAIL', 'JAZZ', 'JEAN',
  'JOBS', 'JOIN', 'JOKE', 'JUMP', 'JUNE', 'JURY', 'JUST', 'KEEN',
  'KEEP', 'KEPT', 'KICK', 'KIDS', 'KILL', 'KIND', 'KING', 'KISS',
  'KNEE', 'KNEW', 'KNIT', 'KNOB', 'KNOT', 'LACE', 'LACK', 'LAID',
  'LAKE', 'LAND', 'LANE', 'LAPS', 'LAST', 'LATE', 'LAWN', 'LAWS',
  'LEAD', 'LEAF', 'LEAN', 'LEAP', 'LEFT', 'LEND', 'LENS', 'LESS',
  'LIAR', 'LIES', 'LIFE', 'LIFT', 'LIKE', 'LIME', 'LIMB', 'LINE',
  'LINK', 'LION', 'LIPS', 'LIST', 'LIVE', 'LOAD', 'LOAN', 'LOCK',
  'LOGO', 'LONG', 'LOOK', 'LOOP', 'LORD', 'LOSE', 'LOSS', 'LOST',
  'LOTS', 'LOUD', 'LOVE', 'LUCK', 'LUMP', 'LUNG', 'LURE', 'MADE',
  'MAIL', 'MAIN', 'MAKE', 'MALE', 'MALL', 'MANY', 'MAPS', 'MARK',
  'MASK', 'MASS', 'MATE', 'MATH', 'MAZE', 'MEAL', 'MEAN', 'MEAT',
  'MEET', 'MELT', 'MEMO', 'MENU', 'MERE', 'MESH', 'MESS', 'MICE',
  'MILD', 'MILE', 'MILK', 'MILL', 'MINE', 'MINI', 'MINT', 'MISS',
  'MODE', 'MOOD', 'MOON', 'MORE', 'MOSS', 'MOST', 'MOVE', 'MUCH',
  'MYTH', 'NAIL', 'NAME', 'NAVY', 'NEAR', 'NEAT', 'NECK', 'NEED',
  'NEWS', 'NEXT', 'NICE', 'NINE', 'NODE', 'NONE', 'NOON', 'NORM',
  'NOSE', 'NOUN', 'NUTS', 'OATH', 'ODDS', 'OKAY', 'ONCE', 'ONLY',
  'ONTO', 'OPEN', 'OPTS', 'ORAL', 'OVER', 'OVEN', 'PACE', 'PACK',
  'PAID', 'PAIN', 'PAIR', 'PALE', 'PALM', 'PANE', 'PARK', 'PART',
  'PASS', 'PAST', 'PATH', 'PEAK', 'PEEL', 'PEER', 'PETS', 'PICK',
  'PILE', 'PINE', 'PINK', 'PIPE', 'PLAN', 'PLAY', 'PLEA', 'PLOT',
  'PLUG', 'PLUS', 'POEM', 'POET', 'POLE', 'POLL', 'POND', 'POOL',
  'POOR', 'POPE', 'PORK', 'PORT', 'POSE', 'POST', 'POUR', 'PRAY',
  'PREY', 'PROP', 'PULL', 'PUMP', 'PURE', 'PUSH', 'QUIT', 'QUIZ',
  'RACE', 'RACK', 'RAGE', 'RAID', 'RAIL', 'RAIN', 'RANK', 'RARE',
  'RATE', 'RAYS', 'REAL', 'REAR', 'RELY', 'RENT', 'REST', 'RICE',
  'RICH', 'RIDE', 'RING', 'RISE', 'RISK', 'ROAD', 'ROCK', 'RODE',
  'ROLE', 'ROLL', 'ROOF', 'ROOM', 'ROOT', 'ROPE', 'ROSE', 'RUIN',
  'RULE', 'RUSH', 'SAFE', 'SAGE', 'SAID', 'SAIL', 'SAKE', 'SALE',
  'SALT', 'SAME', 'SAND', 'SANG', 'SAVE', 'SEAL', 'SEAT', 'SEED',
  'SEEK', 'SEEM', 'SEEN', 'SELF', 'SELL', 'SEND', 'SENT', 'SEPT',
  'SHED', 'SHIP', 'SHOP', 'SHOT', 'SHOW', 'SHUT', 'SICK', 'SIDE',
  'SILK', 'SING', 'SINK', 'SITE', 'SIZE', 'SKIN', 'SKIP', 'SLAM',
  'SLID', 'SLIM', 'SLIP', 'SLOT', 'SLOW', 'SNAP', 'SNOW', 'SOAP',
  'SOCK', 'SOFT', 'SOIL', 'SOLD', 'SOLE', 'SOME', 'SONG', 'SOON',
  'SORT', 'SOUL', 'SOUR', 'SPAN', 'SPIN', 'SPIT', 'SPOT', 'STAR',
  'STAY', 'STEM', 'STEP', 'STEW', 'STOP', 'STUD', 'SUCH', 'SUIT',
  'SURE', 'SURF', 'SWIM', 'TABS', 'TACK', 'TAIL', 'TAKE', 'TALE',
  'TALL', 'TAME', 'TANK', 'TAPE', 'TASK', 'TAXI', 'TEAM', 'TEAR',
  'TELL', 'TEND', 'TENT', 'TERM', 'TEST', 'TEXT', 'THAN', 'THAT',
  'THEM', 'THEN', 'THEY', 'THIN', 'THIS', 'THUS', 'TICK', 'TIDE',
  'TIDY', 'TIED', 'TIER', 'TILE', 'TILL', 'TILT', 'TIME', 'TINY',
  'TIPS', 'TIRE', 'TOAD', 'TOIL', 'TOLD', 'TOLL', 'TOMB', 'TONE',
  'TOOK', 'TOOL', 'TOPS', 'TORN', 'TOSS', 'TOUR', 'TOWN', 'TRAP',
  'TRAY', 'TREE', 'TREK', 'TRIM', 'TRIO', 'TRIP', 'TRUE', 'TUBE',
  'TUCK', 'TUNA', 'TUNE', 'TURN', 'TWIN', 'TYPE', 'UGLY', 'UNDO',
  'UNIT', 'UPON', 'URGE', 'USED', 'USER', 'VAIN', 'VALE', 'VARY',
  'VAST', 'VEIL', 'VEIN', 'VENT', 'VERB', 'VERY', 'VEST', 'VIEW',
  'VINE', 'VISA', 'VOID', 'VOLT', 'VOTE', 'WADE', 'WAGE', 'WAIT',
  'WAKE', 'WALK', 'WALL', 'WAND', 'WARM', 'WARN', 'WARP', 'WARY',
  'WASH', 'WAVE', 'WAYS', 'WEAK', 'WEAR', 'WEED', 'WEEK', 'WELL',
  'WENT', 'WERE', 'WEST', 'WHAT', 'WHEN', 'WHOM', 'WIDE', 'WIFE',
  'WILD', 'WILL', 'WILT', 'WIND', 'WINE', 'WING', 'WINK', 'WIPE',
  'WIRE', 'WISE', 'WISH', 'WITH', 'WOKE', 'WOLF', 'WOMB', 'WOOD',
  'WOOL', 'WORE', 'WORK', 'WORM', 'WORN', 'WRAP', 'YARD', 'YARN',
  'YEAH', 'YEAR', 'YELL', 'YOUR', 'ZEAL', 'ZERO', 'ZINC', 'ZONE',
  'ZOOM',
]);
